import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "./homecomponet/nav";
import "./globals.css";



const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: {
    default: "MERN & Next.js Developer | ConstantineApp", // Shortened to fit under 60 chars
    template: "%s | ConstantineApp", // Removed repetitive phrase
  },
  description: "High-converting web apps built fast. Expert MERN & Next.js developer in Lagos, Nigeria serving clients globally. Specializing in AI APIs & databases.",
  alternates: {
    canonical: "https://yourdomain.com", // FIXES potential GSC indexing errors
  },
  verification: {
    google: "RkG6TiMYnwo7TGEEUOKrC24KiSSiwyNAodOOwQuTcys",
  },
  keywords: [
    "hire nextjs developer lagos",
    "freelance mern stack developer",
    "nextjs website developer near me",
    "react developer for startups",
    "ai api integration services",
    "custom ecommerce web design lagos",
    "affordable web developer portfolio",
    "mongodb nodejs developer remote"
  ],
  authors: [{ name: "ConstantineApp" }],
  creator: "ConstantineApp",
  openGraph: {
    title: "MERN Stack Web Developer & Designer | Global & Local",
    description: "Creating clean, stunning websites to help your business grow. Serving clients worldwide and locally in Lagos, Nigeria.",
    url: "https://yourdomain.com", 
    siteName: "ConstantineApp",
    images: [
      {
        url: "https://constantineapp.vercel.app/og-image.png", 
        width: 1200,
        height: 630,
        alt: "MERN Stack Developer Portfolio Preview",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: { 
    card: "summary_large_image",
    title: "MERN Stack Web Developer & Designer | Global & Local",
    description: "Creating clean, stunning websites to help your business grow.",
    images: ["https://constantineapp.vercel.app/og-image.png"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.className}  antialiased`}
    >

      <body>
        <div className="flex flex-row justify-center items-center">
             <Nav />
        </div>
       
        {children}
      </body>
    </html>
  );
}
