import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "./homecomponet/nav";
import "./globals.css";



const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.className}  antialiased`}
    >

      <body>
        <div className="flex flex-row justify-center items-center">
             <Nav />
        </div>
       
        {children}
      </body>
    </html>
  );
}
