import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "./homecomponet/nav";
import "./globals.css";



const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: {
    default: "Hire Freelance MERN Stack & Next.js Developer | ConstantineApp",
    template: "%s | Freelance Web Developer",
  },
  description: "Need a high-converting website built fast? Freelance MERN stack & Next.js developer in Lagos, Nigeria specializing in AI API integration and databases.",
  verification: {
    google: "SVEyQsS4vdt98mcdGHJfY8t_kBgozWnG8k2NGzlehNQ",
  },
keywords: [
    "hire nextjs developer lagos",
    "freelance mern stack developer",
    "nextjs website developer near me",
    "react developer for startups",
    "ai api integration services",
    "custom ecommerce web design lagos",
    "affordable web developer portfolio",
    "mongodb nodejs developer remote"
  ],
  authors: [{ name: "ConstantineApp" }],
  creator: "ConstantineApp",
  openGraph: {
    title: "MERN Stack Web Developer & Designer | Global & Local",
    description: "Creating clean, stunning websites to help your business grow. Serving clients worldwide and locally in Lagos, Nigeria.",
    url: "https://constantineapp.vercel.app", // Replace with your production domain
    siteName: "ConstantineApp",
    images: [
      {
        url: "https://constantineapp.vercel.app/og-image.png", // Replace with your absolute image asset URL
        width: 1200,
        height: 630,
        alt: "MERN Stack Developer Portfolio Preview",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.className}  antialiased`}
    >

      <body>
        <div className="flex flex-row justify-center items-center">
             <Nav />
        </div>
       
        {children}
      </body>
    </html>
  );
}
